// Keeps the hand-picked builds in data/build-presets.json honest.
//
// Curated content is the standing objection to shipping preset builds at
// all: the perk list is written once and the game keeps moving, so a set
// rots quietly — a perk gets renamed and the preset silently offers three
// perks instead of four, with nothing anywhere saying so. Since the perk
// data is regenerated by a scheduled scraper, that can happen without
// anyone touching this repo.
//
// So the recheck is automated instead of remembered. Every slug is resolved
// against the shipped data on each `npm test`, which CI runs on every push
// and after every data refresh.
import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import type { BuildPreset } from "./build-presets";
import type { Perk } from "./types";

const dataDir = join(dirname(fileURLToPath(import.meta.url)), "..", "data");
const read = <T>(file: string): T => JSON.parse(readFileSync(join(dataDir, file), "utf8")) as T;

const { presets } = read<{ presets: BuildPreset[] }>("build-presets.json");
const perks = read<Perk[]>("perks.json");
const bySlug = new Map(perks.map((perk) => [perk.slug, perk]));

/** Matches the randomizer's own maximum, so a preset can always be applied
 *  whole rather than truncated to whatever the board is set to. */
const PERKS_PER_BUILD = 4;

test("there are presets for both roles", () => {
  for (const role of ["survivor", "killer"] as const) {
    assert.ok(
      presets.some((preset) => preset.role === role),
      `no ${role} presets — the picker would open on an empty list`,
    );
  }
});

test("every preset perk still exists, with the right role", () => {
  const missing: string[] = [];
  for (const preset of presets) {
    for (const slug of preset.perks) {
      const perk = bySlug.get(slug);
      if (!perk) missing.push(`${preset.id}: "${slug}" is not a perk any more`);
      else if (perk.role !== preset.role) {
        missing.push(`${preset.id}: "${slug}" is a ${perk.role} perk in a ${preset.role} preset`);
      }
    }
  }
  assert.deepEqual(missing, [], `${missing.length} preset entries have gone stale`);
});

test("every preset is a full build of distinct perks", () => {
  for (const preset of presets) {
    assert.equal(
      preset.perks.length,
      PERKS_PER_BUILD,
      `${preset.id} has ${preset.perks.length} perks, expected ${PERKS_PER_BUILD}`,
    );
    assert.equal(
      new Set(preset.perks).size,
      preset.perks.length,
      `${preset.id} lists the same perk twice`,
    );
  }
});

test("preset ids are unique", () => {
  const ids = presets.map((preset) => preset.id);
  assert.deepEqual(
    ids.filter((id, i) => ids.indexOf(id) !== i),
    [],
    "two presets share an id",
  );
});

test("every preset is named and described in both languages", () => {
  for (const preset of presets) {
    for (const field of ["name", "description"] as const) {
      for (const lang of ["en", "ru"] as const) {
        assert.ok(
          preset[field][lang]?.trim(),
          `${preset.id} is missing its ${lang} ${field}`,
        );
      }
    }
  }
});
